### ISSUE TITLE
Instructions appear to be missing steps

### ISSUE THREAD

**Issue by BerkSmash1984** [DevMiser/DaVinci_The_Artist#1]
It looks like your screenshots of the instructions left out the actual steps commands for installing MQTT and which config file to edit. Step a. is missing and some screenshots appear broken:

![image](https://github.com/DevMiser/DaVinci_The_Artist/assets/104693081/4a73f198-62d4-4fc3-8017-c40e979eb231)

Can you please fix this? I have DaVinci up and running and now want to implement DaVinci the Artist :) Thanks!

**Comment by DevMiser** [comment]
I will fix this soon.  In the meantime, please note that there is also a pdf of the instructions in the files.  Here is a link: https://github.com/DevMiser/DaVinci_The_Artist/blob/main/DaVinci%20-%20The%20Artist%20Instructions.pdf

**Comment by BerkSmash1984** [comment]
Thanks for the response! Yup, I just saw the PDF and noticed all the
instructions are there. Thanks!

Question for you, is it possible to run DaVinci the Artist without using a
separate RPI connected to a picture frame? For example if DaVinci is hooked
up to a monitor (or you use VNC viewer remotely), could it be configured to
display the DALLE picture being generated on the monitor or VNC viewer? If
so, could you provide an option with instructions for folks who are not
looking to buy another RPI and eInk display? That would be awesome and much
appreciated!

**Comment by DevMiser** [comment]
Yes, that is possible.  I created a new file called DaVinci_The_Artist_No_e_Ink.py.  If you have DaVinci already set up, that program should do what you requested.  If it does not work, please let me know.

**Comment by BerkSmash1984** [comment]
Wow, you are awesome! Thank you for the quick turnaround. I will give it a
go and let you know how it goes!

**Comment by BerkSmash1984** [comment]
Looks like there is a syntax error in at line 160:

![image](https://github.com/DevMiser/DaVinci_The_Artist/assets/104693081/1f835afa-05f5-4132-b637-9563fd1b21b6)

![image](https://github.com/DevMiser/DaVinci_The_Artist/assets/104693081/34b89c80-ef64-427d-a181-ebcfdf15cf84)

**Comment by BerkSmash1984** [comment]
looks like you needed another ")" to close the parathesis at line 159.

**Comment by DevMiser** [comment]
You are correct.  It is fixed now.  I hope you enjoy it.

**Comment by BerkSmash1984** [comment]
It works like a charm, thank you!!
![image](https://github.com/DevMiser/DaVinci_The_Artist/assets/104693081/90b2d2a2-d9cb-4b84-a45d-ad8da0d03e63)
